config/routes.rb
Rails.application.routes.draw do
  resources :videos
  get 'sessions/new'

  resource :users
  resource :sessions

  get 'home/index'
  root 'home#index'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	has_many :videos
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
  	@current_user ||= User.find_by(id: session[:user_id])
  end

  def require_logged_in
  	return true if current_user

  	return redirect_to root_path
  end  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@videos = Video.all
  	@users = User.all
  end
  def login
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create 
  	@user = User.find_by(username: params[:username]).try(:authenticate, params[:password])
  	return render action: 'new' unless @user
  	#logged in 
  	session[:user_id] = @user.id
  	redirect_to videos_path
  end
  def destroy
    session[:user_id] = nil
    redirect_to '/'
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end
  def create 
  	@user = User.new user_params
  	return render action: 'new' unless @user.save
  	redirect_to root_path,  notice: 'Youtube Account Created'
  end
  private
  def user_params
  	params.
  	require(:user).
  	permit(:username, :password, :password_confirmation)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]
  # before_action :require_logged_in

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = current_user.videos.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = current_user.videos.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
      @users = User.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:name, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/home/index.html.erb
<table>


	<tbody>
		
		<% @videos.each do |video|%>
			<tr>
			<td><iframe width="200" height="113" src="https://www.youtube.com/embed/<%= video.body.split("=")[1] %>" frameborder="0" allowfullscreen></iframe></td>
			<td><%= link_to video.name, video_path(video.id)%></a></td> 
			<td><%= video.created_at.strftime("%B %d") %> </td>
			<td><%= @users.find(video.user_id).username%></td> 

			</tr>
		<% end -%>

	</tbody>
</table>

app/views/home/login.html.erb
<h1>login.html.erb</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Youtube-White-Rails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
  	<header>
	
		<div class="logo">
			
			<ul class = "name">	
				<li class="w">
					<%= link_to root_path do %>
   						<%= image_tag ('YouTube-logo-full_color.png') %>
					<% end %> 
				</li>
				<li class="w">|</li>
				<!-- <li class="w"><img class="search" src="search.png" alt="Search"></li> -->
				<li class="w"><input class= "search-input" type="text" placeholder="&#128269; Search"></li>
			</ul>
			<ul class="login">
				<% if !current_user %>
					<li ><%= link_to 'Login', new_sessions_url %></li>
					<li class ="upload">|</li>
					<li><%= link_to 'Sign Up', new_users_url %></li>
				<% else %>
					<li><a href="/videos"><%= current_user.username.capitalize%></a></li>
					<li><%= link_to 'Log Out', logout_path, method: "delete" %></li>
				<% end -%>
			</ul>
		</div>
	
	</header>
	<div class="main">
			
			<section class="video">
				<%= yield %>
			</section>
			<section class="taskbar" >
				<ul class="listvideo">
					<li class ="we"> Guide</li>
					  <% if !current_user %>
			            <li class ="we"></li>
			          <% else %>
			            <li class ="we"><a href="#"><%= image_tag ('profile_l.png'), class: 'line' %> <%= current_user.username.capitalize%></a></li>
			            
			            
			          <% end %>
					
					<li class ="we"><a href="#"><%= image_tag ('world.png'), class: 'line' %> To Watch</a></li>
					<li class ="we"><a href="#"><%= image_tag ('heart.png'), class: 'line' %> Suscriptions</a></li>
					<li class ="we"><a href="#"><%= image_tag ('clipboard.png'), class: 'line' %> History</a></li>
					<li class ="we"><a href="#"><%= image_tag ('watch.png'), class: 'line' %> Watch Later</a></li>
				</ul>
			</section>
		</div>
	</div>
</div>
    
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for @user do |f| %>
	<p>
		<%= f.label :username %>
		<%= f.text_field :username %>

	</p>
	<p>
		<%= f.label :password %>
		<%= f.password_field :password %>

	</p>
	<p>
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation %>

	</p>
	<p>
		<%= f.submit %>

	</p>
<% end %>

app/views/videos/_form.html.erb
<%= form_with(model: video, local: true) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :video_user_id %>
  </div> -->

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :video_name %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_area :body, id: :video_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Videos</h1>

<table>
  <thead>
    <tr>
      
      <th>Name</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><iframe width="200" height="113" src="https://www.youtube.com/embed/<%= video.body.split("=")[1] %>" frameborder="0" allowfullscreen></iframe></td>
        <td><%= video.name %></td>
        
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>



<p>
  <strong>Name:</strong>
  <%= @video.name %>
</p>

<p>
  <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= @video.body.split("=")[1] %>" frameborder="0" allowfullscreen></iframe>
</p>
<p>
	<strong>Uploaded by:</strong>
	<%= @users.find(@video.user_id).username %>
</p>

<% if !current_user %>
	<%= link_to 'Back', root_path %>
<% else %>
	<%= link_to 'Back', videos_path %>
<% end -%>